### ISSUE TITLE
relocation R_X86_64_32S against `a local symbol'  problem

### ISSUE THREAD

**Issue by noca** [tiwe-de/libpam-pwdfile#1]
Thanks for the work about this module, it's cool!

There's a little bug here:

When I compiled the code in Centos, it will end up by this error:

 /usr/bin/ld: dynamic/pam_pwdfile.o: relocation R_X86_64_32S against `a local symbol' can not be used when making a shared object; recompile with -fPIC
dynamic/pam_pwdfile.o: could not read symbols: Bad value
collect2: ld returned 1 exit status

And I certainly followed the error instruction to add '-fPIC' to replace:

CFLAGS += -D_BSD_SOURCE 

by :

CFLAGS += -D_BSD_SOURCE -fPIC

Is that a by design or just a missing of  '-fPIC'.

By the way:

The compilation instruction is a little too cost, my way is:
1. Download the PAM tarball(The tarball in linux kernel is removed):
wget -c http://pkgs.fedoraproject.org/repo/pkgs/pam/Linux-PAM-0.75.tar.bz2/2f19d6f6908e46d8b4d115e9f842d147/Linux-PAM-0.75.tar.bz2
2. untar it and configure
tar xvjf Linux-PAM-0.75.tar.bz2 && configure && cd Linux-PAM-0.75/modules
3. get pwdfile code and compile it(don't forget add the -fPIC):
git clone git://github.com/tiwe-de/libpam-pwdfile.git && cd libpam-pwdfile && make all

**Comment by tiwe-de** [comment]
Building the module inside the pam source tree is the "old" way of doing it and I haven't tested it. I guess your distribution already has PAM libs installed. Please install development headers and try contrib/Makefile.standalone or debian/Makefile (from the old_debian branch, you'll also need to apply the visibility patch).

The Makefile(s) will receive an update when I reorganize the source. (I still have to find out if the "broken md5" really makes sense on little endian.)
