### ISSUE TITLE
Lacking support for $apr1$ hashed passwords

### ISSUE THREAD

**Issue by xlatb** [tiwe-de/libpam-pwdfile#2]
Apache's htpasswd uses a slightly different hashing method (signature $apr1$) for MD5-encoded passwords than the method supported by libpam-pwdfile (signature $1$). That leads to situations like this: http://serverfault.com/questions/450214/vsftpd-will-not-accept-passwords-encrypted-with-md5

It is possible to still use htpasswd with the -d flag, but that leads to less-secure hashes and an 8-character password length limit.

Here is a patch to enable support for Apache-style MD5 passwords in libpam-pwdfile:
https://gist.github.com/powerpiglet/b3b1c9f68afc39faf85d

**Comment by tiwe-de** [comment]
Please use `mkpasswd -m sha-512` to get something you can use with both apache and libpam-pwdfile when using glibc >= 2.7 and [this very small patch to libpam-pwdfile](https://github.com/tiwe-de/libpam-pwdfile/blob/old_debian/debian/patches/regular_crypt).

My goal for this project is to have as little copied-and-patched code as possible, so if you really think $apr1$ hashes should be supported try getting it into glibc.

Both $apr1$ and $1$ hashes can be considered too weak against GPU-based attacks.

**Comment by tiwe-de** [comment]
the patch to correctly use libc's crypt is not needed anymore with the latest release.

BTW: your proposed patch doesn't implement the apr1 stuff

**Comment by xlatb** [comment]
> BTW: your proposed patch doesn't implement the apr1 stuff

$1$ and $apr1$ are the same algorithm, just with a different magic signature, so the $1$ implementation is reused. All it needs is a flag telling it which signature to select.

The resulting hashes are different, because the algorithm mixes the signature into the stream of data to be hashed.
