### ISSUE TITLE
pwd file owned by root with 600 permission read error

### ISSUE THREAD

**Issue by Artiom-M** [tiwe-de/libpam-pwdfile#3]
Looking into you code I see
**if (!(pwdfile = fopen(pwdfilename, "r"))) {**
directly in the PAM module code. This means that if this module is called by non root application (screensaver, su, etc.) it can no be read. And if it can be read, this means it's permissions are world readable which is not good for password files.
I have the same issue with my PAM module and I found that authorization part should be put to a separate NSS module.

**Comment by tiwe-de** [comment]
That's exactly why pam_unix uses a suid/sgid binary, unix_chkpwd(8).
libpam-pwdfile is primarily intended for daemons; here the pwdfile can be made accessible to them easily, setfacl might be your friend.
