### ISSUE TITLE
Updated package for Precise?

### ISSUE THREAD

**Issue by Rikk** [tiwe-de/libpam-pwdfile#4]
Any chance you would push an updated version for Ubuntu Precise?
It would be good for security, considering the version available in repository (libpam-pwdfile (0.99-4)) does not support hashes better than md5 and wasn't updated in a long time.
Otherwise, do you know any other Ubuntu/Deb package for reading password files?

Thanks

**Comment by tiwe-de** [comment]
[0.99-5 from wheezy](https://packages.debian.org/wheezy/libpam-pwdfile) has the feature you want and can be installed in precise (tested on amd64). You can also try later versions.

You may also do your own backport by just building the source package and/or follow the [instructions for requesting a backport in ubuntu](https://wiki.ubuntu.com/UbuntuBackports).

**Comment by Rikk** [comment]
Would like to thank you for the tip, I figured out the [Pinning](https://help.ubuntu.com/community/PinningHowto) way to install updates from newer releases, and installed 1.0-1 from Trusty as soon I see the deps match.
