### ISSUE TITLE
undefined symbol: pam_get_authtok

### ISSUE THREAD

**Issue by milky-milk** [tiwe-de/libpam-pwdfile#5]
Hello.
I want to use this module in old version of CentOS 5.
Is there any way to use it on this distro? I've tried to use it with ssh, but it fails to load with this message:

```
Jun 16 21:40:17 localhost sshd[3738]: PAM unable to dlopen(/lib64/security/pam_pwdfile.so)
Jun 16 21:40:17 localhost sshd[3738]: PAM [error: /lib64/security/pam_pwdfile.so: undefined symbol: pam_get_authtok]
Jun 16 21:40:17 localhost sshd[3738]: PAM adding faulty module: /lib64/security/pam_pwdfile.so
```

**Comment by tiwe-de** [comment]
you might try either of:
- somehow revert 0437f4656f1d5a541b4ab951c457fae19f8deee4
- use 86c95423b2908869ee42f9f40896a0bb0b773cf4 (previous commit) and apply debian/patches/regular_crypt from 09cf8097c6bdf0011cf78c6000c6dcbdb7618cf0
- update pam to 1.1 or later
- update whole distribution
